// <auto-generated />
namespace JCold_UVU_MVC_Inventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class supplyintvaluechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supplyintvaluechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201804190021053_supplyintvaluechange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
